module.exports.config = {
  name: "tiktokvip",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "cuteo",
  description: "xem video tiktok có sẵn trong lệnh được update lên bởi thanh hiền",
  commandCategory: "video tiktok",
  usages: "tiktokvip",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/RBX3SFu.mp4", "https://i.imgur.com/R1grkur.mp4", "https://i.imgur.com/1xmkAqC.mp4", "https://i.imgur.com/wU5eX10.mp4", "https://i.imgur.com/eb6iXCi.mp4", "https://i.imgur.com/6DS4KJb.mp4", "https://i.imgur.com/912ewNg.mp4", "https://i.imgur.com/TrMd0NX.mp4", "https://i.imgur.com/tGcYHMK.mp4", "https://i.imgur.com/cHaERU7.mp4", "https://i.imgur.com/0EO53h4.mp4", "https://i.imgur.com/N4X85FG.mp4", "https://i.imgur.com/RImJrNQ.mp4", "https://i.imgur.com/gr5Qlwv.mp4", "https://i.imgur.com/PUJNjOJ.mp4", "https://i.imgur.com/R2rpbbA.mp4", "https://i.imgur.com/7cbA4P1.mp4", "https://i.imgur.com/1NXDYwt.mp4", "https://i.imgur.com/k5AC5Yr.mp4", "https://i.imgur.com/rqpz8L5.mp4", "https://i.imgur.com/FBkbIm1.mp4", "https://i.imgur.com/j98mQ0S.mp4", "https://i.imgur.com/2RgZjCn.mp4", "https://i.imgur.com/FRr78ck.mp4", "https://i.imgur.com/TvuYfnp.mp4", "https://i.imgur.com/SGLiQZi.mp4", "https://i.imgur.com/eFEeOL8.mp4", "https://i.imgur.com/aBVevHL.mp4", "https://i.imgur.com/S8VIXTo.mp4",
    "https://i.imgur.com/ELnTT9d.mp4",
    "https://i.imgur.com/0oEHyCO.mp4",
    "https://i.imgur.com/Cstt4YV.mp4",
    "https://i.imgur.com/u18ceLR.mp4",
    "https://i.imgur.com/trjTea8.mp4",
    "https://i.imgur.com/rtnHMmE.mp4",
    "https://i.imgur.com/xMnh69G.mp4",
    "https://i.imgur.com/1KkxuaR.mp4",
    "https://i.imgur.com/9uxk2EH.mp4",
    "https://i.imgur.com/CbyziGj.mp4",
    "https://i.imgur.com/Dif7HOi.mp4", 
    "https://i.imgur.com/b47ElB3.mp4",
    "https://i.imgur.com/u8J7TFA.mp4",
    "https://i.imgur.com/0hRYlET.mp4",
    "https://i.imgur.com/z92U7Wa.mp4",
    "https://i.imgur.com/t9JGn1P.mp4",
    "https://i.imgur.com/fdAIrgt.mp4", 
    "https://i.imgur.com/mWzZEaB.mp4",
    "https://i.imgur.com/R4WhtDS.mp4",
    "https://i.imgur.com/gRMlB9x.mp4",
    "https://i.imgur.com/6ZFqWLB.mp4",
    "https://i.imgur.com/TRhthf6.mp4",
    "https://i.imgur.com/Qit7yVE.mp4",
    "https://i.imgur.com/erCfWHm.mp4",
    "https://i.imgur.com/PPeGM7F.mp4",
    "https://i.imgur.com/UKbKiRC.mp4",
    "https://i.imgur.com/Mo1yJb2.mp4",
    "https://i.imgur.com/DiZwOv8.mp4",
    "https://i.imgur.com/8jnQQak.mp4",
    "https://i.imgur.com/kho40y9.mp4",
    "https://i.imgur.com/ykqFdwc.mp4",
    "https://i.imgur.com/RyzeK2O.mp4",
    "https://i.imgur.com/4srbQ6f.mp4",
    "https://i.imgur.com/VXsVjIZ.mp4",
    "https://i.imgur.com/SkxlPWT.mp4",
    "https://i.imgur.com/4T3vHzc.mp4",
    "https://i.imgur.com/wYYyJYS.mp4",
    "https://i.imgur.com/jAcSkzT.mp4",
    "https://i.imgur.com/PgxhFNT.mp4",
    "https://i.imgur.com/mZlv2ec.mp4",
    "https://i.imgur.com/DuVBey2.mp4",
    "https://i.imgur.com/ky3lTqm.mp4",
    "https://i.imgur.com/uhDrQ5y.mp4",
    "https://i.imgur.com/s6b0vUz.mp4",
    "https://i.imgur.com/amqqsCv.mp4",
    "https://i.imgur.com/QYahyOh.mp4",
    "https://i.imgur.com/51RXzMd.mp4",
    "https://i.imgur.com/TOnLrFf.mp4",
    "https://i.imgur.com/oxhzd9I.mp4",
    "https://i.imgur.com/P5psIWI.mp4",
    "https://i.imgur.com/ND05XWc.mp4",
    "https://i.imgur.com/LjeRX6U.mp4",
  "https://i.imgur.com/8ZRmOAD.mp4",
    "https://i.imgur.com/1ImH1zN.mp4",
    "https://i.imgur.com/RoBVnq3.mp4",
    "https://i.imgur.com/N8eDDhD.mp4",
    "https://i.imgur.com/knllHvQ.mp4",
    "https://i.imgur.com/xgq5BEw.mp4",
    "https://i.imgur.com/3oQkewF.mp4",
    "https://i.imgur.com/wJwiPls.mp4",
    "https://i.imgur.com/wgIjYly.mp4",
    "https://i.imgur.com/dFnr1de.mp4",
    "https://i.imgur.com/J9Ndp1D.mp4",
    "https://i.imgur.com/sXkwmO9.mp4",
    "https://i.imgur.com/jlWTXry.mp4",
    "https://i.imgur.com/726dBBY.mp4",
    "https://i.imgur.com/chPnflC.mp4",
    "https://i.imgur.com/quyYi7W.mp4",
    "https://i.imgur.com/Y48yrAS.mp4",
    "https://i.imgur.com/g4DRDYk.mp4",
    "https://i.imgur.com/tBPD222.mp4",
    "https://i.imgur.com/1JI1szk.mp4",
    "https://i.imgur.com/RCjbClt.mp4", "https://i.imgur.com/rnyc0Wy.mp4",
    "https://i.imgur.com/WYoHZnZ.mp4",
    "https://i.imgur.com/UKg6pGk.mp4",
    "https://i.imgur.com/7NgUJuY.mp4",
    "https://i.imgur.com/hMUVTpT.mp4",
    "https://i.imgur.com/5o6BmfE.mp4",
    "https://i.imgur.com/84k2RR2.mp4",
    "https://i.imgur.com/2P9v3GV.mp4",
    "https://i.imgur.com/MVijVWU.mp4",
    "https://i.imgur.com/HJI1Mn7.mp4",
    ];
  var callback = () => api.sendMessage({body:`🌺梁Update bởi ADMIN ʚᥫບ七ÈᎧɞ梁🌺
                            𖤂◡̈𖤂
       Admin: Nguyễn Hữu Thanh Hiền
                      ----ᥫບ 七ÈᎧ----`,attachment: fs.createReadStream(__dirname + "/cache/5.mp4")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.mp4")); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.mp4")).on("close",() => callback());
   };
 